---
name: Update

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull
        env:
          deploy_key: ${{secrets.deploy_key}}
          known_hosts: ${{secrets.known_hosts}}
        run: |
          mkdir -p ${HOME}/.ssh
          printf "%s\n" "$known_hosts" > ${HOME}/.ssh/known_hosts
          printf "%s\n" "$deploy_key" > ${HOME}/.ssh/id_rsa 
          chmod 600 ${HOME}/.ssh/id_rsa
          rsync -a --delete ./ github@romain-laurent.me:/home/github/portfolio/ # --delete will remove files if they were removed from the repository
          # So if it's a problem, just remove the option
